pymacoop/apps/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path(
        "login/",
        views.LoginView.as_view(),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "password-change/",
        views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "edit/",
        views.edit_account,
        name="edit",
    ),
    path("workers", views.list_workers, name="workers_list"),
    path("workers/add", views.add_worker, name="workers_add"),
    path("workers/<int:pk>/edit", views.edit_worker, name="workers_edit"),
]

pymacoop/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("accounts/", include("pymacoop.apps.accounts.urls", namespace="accounts")),
    path("", include("pymacoop.apps.home.urls")),
    path(
        "faircalendar/",
        include("pymacoop.apps.faircalendar.urls", namespace="faircalendar"),
    ),
    path("crm/", include("pymacoop.apps.crm.urls", namespace="crm")),
]

pymacoop/apps/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from dj_fluent import format_value as t


class User(AbstractUser):
    def __str__(self):
        if self.first_name and self.last_name:
            return f"{self.first_name} {self.last_name}"

        if self.first_name:
            return self.first_name

        return self.username


class WorkerManager(models.Manager):
    def with_user(self):
        return self.select_related("user")


class Worker(models.Model):
    objects = WorkerManager()

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name=t("accounts-workers-user-name"),
    )
    joining_date = models.DateField(
        verbose_name=t("accounts-workers-joining_date-name"),
    )
    leaving_date = models.DateField(
        blank=True,
        null=True,
        verbose_name=t("accounts-workers-leaving_date-name"),
    )
    annual_salary = models.IntegerField(
        default=0,
        verbose_name=t("accounts-workers-annual_salary-name"),
    )
    transport_fee = models.IntegerField(
        default=0,
        verbose_name=t("accounts-workers-transport_fee-name"),
    )
    sustainable_mobility_fee = models.IntegerField(
        default=0,
        verbose_name=t("accounts-workers-sustainable_mobility_fee-name"),
    )
    executive_position = models.BooleanField(
        default=True,
        verbose_name=t("accounts-workers-executive_position-name"),
    )
    health_insurance = models.BooleanField(
        default=True,
        verbose_name=t("accounts-workers-health_insurance-name"),
    )
    contract = models.CharField(
        max_length=3,
        choices=[
            ("cdi", t("accounts-workers-contract-cdi")),
            ("cdd", t("accounts-workers-contract-cdd")),
        ],
        default="cdi",
        verbose_name=t("accounts-workers-contract-name"),
    )
    working_time = models.CharField(
        max_length=9,
        choices=[
            ("full_time", t("accounts-workers-working_time-full_time")),
            ("part_time", t("accounts-workers-working_time-part_time")),
        ],
        default="full_time",
        verbose_name=t("accounts-workers-working_time-name"),
    )

    class Meta:
        verbose_name = t("accounts-workers-verbose_name")

    def __str__(self):
        return str(self.user)

pymacoop/apps/accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm
from django.urls.base import reverse_lazy

from dj_fluent import format_value as t

from ..forms.base import BaseForm
from ..forms.widgets import BooleanSelect
from .models import User, Worker


class LoginForm(BaseForm, AuthenticationForm):
    username = UsernameField(
        label=t("accounts-login-form-username"),
    )
    password = forms.CharField(
        label=t("accounts-login-form-password"),
        strip=False,
        widget=forms.PasswordInput,
    )


class UserCreationForm(BaseUserCreationForm):
    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
            "password1",
            "password2",
        )


class ObfuscatedPasswordWidget(forms.Widget):
    template_name = "accounts/widgets/obfuscated_password.html"
    read_only = True


class ObfuscatedPasswordField(forms.Field):
    widget = ObfuscatedPasswordWidget


class UserChangeForm(forms.ModelForm):
    password = ObfuscatedPasswordField(
        label=t("accounts-login-form-password"),
        help_text=t("accounts-login-form-password-change"),
        required=False,
        disabled=True,
    )
    password_change_url = reverse_lazy("accounts:password_change")

    instance: User

    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
            "password",
        )
        field_classes = {"username": UsernameField}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        password = self.fields["password"]
        start = f'<a class="text-blue-500" href="{self.password_change_url}">'
        end = "</a>"
        password.help_text = password.help_text.format(start=start, end=end)


class WorkerForm(forms.ModelForm):
    class Meta:
        model = Worker
        fields = (
            "joining_date",
            "leaving_date",
            "annual_salary",
            "transport_fee",
            "sustainable_mobility_fee",
            "health_insurance",
            "executive_position",
            "contract",
            "working_time",
        )
        widgets = {
            "joining_date": forms.DateInput(attrs={"type": "date"}),
            "leaving_date": forms.DateInput(attrs={"type": "date"}),
            "health_insurance": BooleanSelect(),
            "executive_position": BooleanSelect(),
        }

pymacoop/apps/accounts/views.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls.base import reverse, reverse_lazy
from django.views.decorators.http import require_http_methods
from django.views.generic.edit import UpdateView
from djaq import DjaqQuery as DQ

from dj_fluent import format_value as t

from ...stubs import AuthenticatedHttpRequest
from ..tables.utils import paginate
from .forms import LoginForm, UserChangeForm, UserCreationForm, WorkerForm
from .models import User, Worker
from .tables import WorkersTable


class LoginView(auth_views.LoginView):
    template_name = "accounts/login.html"
    form_class = LoginForm


def edit_account(request):
    if request.method == "POST":
        form = UserChangeForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect("home")

    return render(
        request,
        "accounts/edit.html",
        context={
            "form": UserChangeForm(instance=request.user),
            "breadcrumb_items": [
                {"title": t("accounts-edit-title")},
            ],
        },
    )


class AccountEditView(LoginRequiredMixin, UpdateView):
    template_name = "accounts/edit.html"
    form_class = UserChangeForm
    queryset = User.objects.all()
    success_url = reverse_lazy("home")

    request: AuthenticatedHttpRequest

    def get_object(self, queryset=None) -> User:
        return self.request.user

    def get_context_data(self, **kwargs) -> dict:
        title = t("accounts-edit-title")

        return {
            **super().get_context_data(**kwargs),
            "translations": {"title": title},
            "breadcrumb_items": [
                {"title": title},
            ],
        }


class PasswordChangeView(auth_views.PasswordChangeView):
    template_name = "accounts/password_change.html"
    success_url = reverse_lazy("accounts:edit")

    def get_context_data(self, **kwargs) -> dict:
        title = t("accounts-password-change")

        return {
            **super().get_context_data(**kwargs),
            "translations": {
                "title": title,
            },
            "breadcrumb_items": [
                {"title": t("accounts-title"), "path": reverse("accounts:edit")},
                {"title": title},
            ],
        }


def list_workers(request):
    workers = list(
        DQ(
            "Worker",
            """
            id as pk,
            concat(user.first_name, ' ', user.last_name) as user,
            """,
        ).objs()
    )

    table = WorkersTable(workers)
    table = paginate(table, request)

    title = t("accounts-workers-title")

    return render(
        request,
        "accounts/workers/list.html",
        {
            "title": title,
            "table": table,
            "breadcrumb_items": [
                {"title": title},
            ],
        },
    )


@require_http_methods(["GET", "POST"])
def add_worker(request):
    if request.method == "POST":
        user_form = UserCreationForm(request.POST)
        worker_form = WorkerForm(request.POST)
        if user_form.is_valid() and worker_form.is_valid():
            user = user_form.save()
            worker_form.instance.user = user
            worker_form.save()
            return redirect("accounts:workers_list")
    else:
        user_form = UserCreationForm()
        worker_form = WorkerForm()

    title = t("accounts-workers-add-title")

    return render(
        request,
        "accounts/workers/add.html",
        {
            "title": title,
            "user_form": user_form,
            "worker_form": worker_form,
            "breadcrumb_items": [
                {"title": t("accounts-title")},
                {
                    "title": t("accounts-workers-title"),
                    "path": reverse("accounts:workers_list"),
                },
                {"title": title},
            ],
        },
    )


@require_http_methods(["GET", "POST"])
def edit_worker(request, pk):
    worker = get_object_or_404(Worker.objects.with_user(), pk=pk)

    if request.method == "POST":
        form = WorkerForm(request.POST, instance=worker)
        if form.is_valid():
            form.save()
            return redirect("accounts:workers_list")
    else:
        form = WorkerForm(instance=worker)

    title = t("accounts-workers-edit-title", {"worker": worker})

    return render(
        request,
        "accounts/workers/edit.html",
        {
            "title": title,
            "form": form,
            "breadcrumb_items": [
                {
                    "title": t("accounts-workers-title"),
                    "path": reverse("accounts:workers_list"),
                },
                {"title": title},
            ],
        },
    )

pymacoop/apps/accounts/templates/accounts/edit.html
{% extends "layouts/default.html" %}
{% load dj_fluent %}

{% block content %}
{% include 'components/breadcrumb.html' with items=breadcrumb_items %}

<h1>
  {{ 'accounts-edit-title'|translate|capfirst }}
</h1>

{% url "accounts:edit" as action %}
<form method="POST">
  {% csrf_token %}

  {% include 'forms/row.html' with field=form.username group_class="app-input-group" %}
  {% include 'forms/row.html' with field=form.first_name group_class="app-input-group" %}
  {% include 'forms/row.html' with field=form.last_name group_class="app-input-group" %}
  {% include 'forms/row.html' with field=form.email group_class="app-input-group" %}
  {% include 'forms/row.html' with field=form.password group_class="app-input-group" %}

  <button type="submit" class="app-btn">
    {{ 'common-form-save'|translate|capfirst }}
  </button>
</form>
{% endblock content %}

pymacoop/apps/accounts/templates/accounts/login.html
{% extends "layouts/blank.html" %}
{% load static dj_fluent %}

{% block page %}

<div class="app-login">
    <div class="app-login__card">
        <div class="app-login__img">
            <img aria-hidden="true" src="{% static 'images/login-office.jpeg' %}" />
        </div>

        <div class="app-login__content">
            <h1 class="app-login__title">
                {{ "accounts-login-title"|translate }}
            </h1>

            {% if next %}
                <p class="app-login__next">
                    {% if user.is_authenticated %}
                        {{ "accounts-login-next-authenticated"|translate }}
                    {% else %}
                        {{ "accounts-login-next"|translate }}
                    {% endif %}
                </p>
            {% endif %}

            <form method="POST" action="{% url 'accounts:login' %}">
                {% csrf_token %}
                {% include "components/server_errors.html" with errorlist=form.non_field_errors %}
    
                <div class="app-input-group">
                    {{ form.username.label_tag }}
                    {{ form.username }}
                </div>
    
                <div class="app-input-group">
                    {{ form.password.label_tag }}
                    {{ form.password }}
                </div>
 
                <input type="hidden" name="next" value="{{ next }}">
    
                <button type="submit" class="app-btn app-btn--full">
                    {{ 'accounts-login-form-button'|translate }}
                </button>
            </form>

            <p class="app-login__password-reset">
                <a href="{% url 'accounts:password_reset' %}">
                    {{ "accounts-login-form-password-lost"|translate }}
                </a>
            </p>

            <hr />
        </div>

    </div>
</div>

{% endblock page %}

pymacoop/apps/accounts/templates/accounts/password_change.html
{% extends "layouts/default.html" %}
{% load i18n static %}

{% block content %}
{% component "breadcrumb" items=breadcrumb_items %}

<h1>{{ translations.title|capfirst }}</h1>

{% url "accounts:password_change" as action %}
{{ form.as_p }}

{% endblock %}