pymacoop/apps/faircalendar/urls.py
from django.urls import path

from . import views

app_name = "faircalendar"

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "events/add/<int:year>/<int:month>/<int:day>",
        views.add_event,
        name="events_add",
    ),
    path("events/<int:pk>/edit", views.edit_event, name="events_edit"),
    path("events/<int:pk>/delete", views.delete_event, name="events_delete"),
]

pymacoop/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("accounts/", include("pymacoop.apps.accounts.urls", namespace="accounts")),
    path("", include("pymacoop.apps.home.urls")),
    path(
        "faircalendar/",
        include("pymacoop.apps.faircalendar.urls", namespace="faircalendar"),
    ),
    path("crm/", include("pymacoop.apps.crm.urls", namespace="crm")),
]

pymacoop/apps/faircalendar/models.py
from django.db import models

from dj_fluent import format_value as t


class Event(models.Model):
    type = models.CharField(
        max_length=24,
        choices=[
            ("mission", t("faircalendar-event-type-mission")),
            ("support", t("faircalendar-event-type-support")),
            ("dojo", t("faircalendar-event-type-dojo")),
            ("formation_conference", t("faircalendar-event-type-formation_conference")),
            ("other", t("faircalendar-event-type-other")),
        ],
        verbose_name=t("faircalendar-event-type-name"),
    )
    date = models.DateField(
        verbose_name=t("faircalendar-event-date-name"),
    )
    project = models.ForeignKey(
        "crm.Project",
        on_delete=models.CASCADE,
        verbose_name=t("faircalendar-event-project-name"),
    )
    user = models.ForeignKey(
        "accounts.User",
        on_delete=models.CASCADE,
        verbose_name=t("faircalendar-event-user-name"),
    )
    comment = models.CharField(
        max_length=256, blank=True, verbose_name=t("faircalendar-event-comment-name")
    )

    class Meta:
        verbose_name = t("faircalendar-event-verbose_name")

    def __str__(self) -> str:
        return self.date.isoformat()

pymacoop/apps/faircalendar/forms.py
from django import forms

from .models import Event


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ("type", "date", "project", "comment")

pymacoop/apps/faircalendar/views.py
import datetime as dt
import json

from django.core.serializers.json import DjangoJSONEncoder
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils import formats
from django.views.decorators.http import require_GET, require_http_methods, require_POST
from djaq import DjaqQuery as DQ

from dj_fluent import format_value as t

from .forms import EventForm
from .models import Event


@require_GET
def index(request):
    events = list(
        DQ(
            "Event",
            """
            id as pk,
            type,
            date,
            project.name
            """,
        )
        .where("user.id == {user_id}")
        .context({"user_id": request.user.pk})
        .objs()
    )

    fullcalendar_events = [
        {
            # See: https://fullcalendar.io/docs/event-object
            "type": event.type,
            "start": event.date,
            "end": event.date,
            "title": (
                event.project_name
                if event.type == "mission"
                else f"faircalendar-event-type-{event.type}"
            ),
            "url": reverse("faircalendar:events_edit", kwargs={"pk": event.pk}),
            "textColor": f"var(--event-{event.type}-text)",
            "backgroundColor": f"var(--event-{event.type}-background)",
            "borderColor": f"var(--event-{event.type}-border)",
        }
        for event in events
    ]

    fullcalendar_events_json = json.dumps(fullcalendar_events, cls=DjangoJSONEncoder)

    return render(
        request,
        "faircalendar/index.html",
        {"fullcalendar_events_json": fullcalendar_events_json},
    )


@require_http_methods(["GET", "POST"])
def add_event(request, year, month, day):
    if request.method == "POST":
        form = EventForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("faircalendar:index")
    else:
        form = EventForm(
            initial={
                "date": dt.date(year, month, day),
                "user": request.user,
            }
        )

    title = t(
        "faircalendar-event-add-title",
        {"date": formats.localize(form["date"].value())},
    )

    return render(
        request,
        "faircalendar/events/add.html",
        {
            "title": title,
            "form": form,
            "breadcrumb_items": [
                {
                    "title": t("faircalendar-title"),
                    "path": reverse("faircalendar:index"),
                },
                {"title": title},
            ],
        },
    )


@require_http_methods(["GET", "POST"])
def edit_event(request, pk):
    event = get_object_or_404(Event.objects.select_related("user"), pk=pk)

    if request.method == "POST":
        form = EventForm(request.POST, instance=event)

        if form.is_valid():
            form.save()
            return redirect("faircalendar:index")
    else:
        form = EventForm(instance=event)

    return render(
        request,
        "faircalendar/events/edit.html",
        {"form": form},
    )


@require_POST
def delete_event(request, pk):
    event = get_object_or_404(Event.objects.only("id"), pk=pk)
    event.delete()
    return redirect("faircalendar:index")

pymacoop/apps/faircalendar/templates/faircalendar/events/add.html
{% extends "layouts/default.html" %}
{% load dj_fluent %}

{% block content %}
{% include 'components/breadcrumb.html' with items=breadcrumb_items %}

<h1>
    {{ title }}
</h1>

<form method="POST">
    {% csrf_token %}

    {% include 'forms/row.html' with field=form.type group_class="app-input-group" %}
    {% include 'forms/row.html' with field=form.date group_class="app-input-group" hidden=True %}
    {% include 'forms/row.html' with field=form.project group_class="app-input-group" %}
    {% include 'forms/row.html' with field=form.user hidden=True %}
    {% include 'forms/row.html' with field=form.comment group_class="app-input-group" %}

    <button type="submit" class="app-btn">
        {{ "common-form-save"|translate|capfirst }}
    </button>
</form>

{% endblock content %}

pymacoop/apps/faircalendar/templates/faircalendar/events/edit.html
{% extends "layouts/default.html" %}
{% load dj_fluent %}

{% block content %}
{% include 'components/breadcrumb.html' with items=breadcrumb_items %}

<h1>
    {% translate 'faircalendar-event-edit-title' date=form.date.value %}
</h1>

<form method="POST">
    {% csrf_token %}

    {% include 'forms/row.html' with field=form.type group_class="app-input-group" %}
    {% include 'forms/row.html' with field=form.date group_class="app-input-group" hidden=True %}
    {% include 'forms/row.html' with field=form.project group_class="app-input-group" %}
    {% include 'forms/row.html' with field=form.comment group_class="app-input-group" %}

    <div class="app-flex-between">
        <button type="submit" class="app-btn">
            {{ "common-form-save"|translate|capfirst }}
        </button>

        <button type="button" form="delete-form" data-controller="trigger" class="delete-form-trigger app-btn app-btn--danger">
            {{ 'common-form-delete'|translate }}
        </button>
    </div>
</form>

<div data-controller="modal form-submit" data-modal-key-value="confirm" data-modal-trigger-outlet=".delete-form-trigger" data-action="modal:submit->form-submit#submitForm">
    <dialog data-modal-target="dialog">
        <form method="dialog">
            <p>{% translate 'common-form-delete-confirm' obj='faircalendar-event-name'|translate %}</p>
            <button class="app-btn app-btn--secondary" value="close">
                {{ 'common-form-delete-confirm-no'|translate }}
            </button>
            <button class="app-btn" value="confirm">
                {{ 'common-form-delete-confirm-yes'|translate }}
            </button>
        </form>
    </dialog>

    <form
        id="delete-form"
        method="POST"
        action="{% url 'faircalendar:events_delete' pk=form.instance.pk %}"
        data-form-submit-target="form"
        >    
        {% csrf_token %}
    </form>
</div>
{% endblock content %}